version: '3'

services:

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    expose:
      - 8081
      - 5003
    ports:
      - "8081:8081"
      - "5003:5003"
    volumes:
      - "/nexus-data:/nexus-data"
